# Generated by Django 6.0 on 2025-12-07 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK / Max')], max_length=50, verbose_name='Платформа')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('api_token', models.CharField(help_text='Токен для доступа к API платформы', max_length=500, verbose_name='API Token')),
                ('channel_id', models.CharField(help_text='ID канала Telegram или группы VK', max_length=100, verbose_name='ID канала/группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('project', '🏊 Новый проект'), ('tip', '💡 Полезный совет'), ('promo', '🎁 Акция/Скидка'), ('case', '📸 Кейс/Отзыв'), ('edu', '📚 Образовательный'), ('news', '📰 Новости компании')], max_length=50, unique=True, verbose_name='Тип')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_hashtags', models.TextField(blank=True, help_text='Каждый хештег с новой строки', verbose_name='Хештеги по умолчанию')),
            ],
            options={
                'verbose_name': 'Категория постов',
                'verbose_name_plural': 'Категории постов',
            },
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('pool_type', models.CharField(choices=[('concrete', 'Бетонный'), ('composite', 'Композитный'), ('frame', 'Каркасный'), ('inflatable', 'Надувной'), ('indoor', 'Крытый'), ('outdoor', 'Открытый')], max_length=50, verbose_name='Тип бассейна')),
                ('size', models.CharField(help_text='Например: 8x4 м, глубина 1.5-2 м', max_length=50, verbose_name='Размеры')),
                ('features', models.TextField(blank=True, help_text='Противоток, подсветка, джакузи и т.д.', verbose_name='Особенности')),
                ('location', models.CharField(blank=True, help_text='Город или район', max_length=200, verbose_name='Локация')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('images', models.JSONField(default=list, help_text='Список URL изображений', verbose_name='Изображения')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='Главное изображение')),
                ('source_url', models.URLField(blank=True, help_text='URL страницы проекта на сайте', verbose_name='Источник')),
                ('is_published', models.BooleanField(default=False, help_text='Был ли уже создан пост по этому проекту', verbose_name='Пост создан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект бассейна',
                'verbose_name_plural': 'Проекты бассейнов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('template_text', models.TextField(help_text='Используйте {title}, {description}, {size}, {features}, {location} как плейсхолдеры', verbose_name='Текст шаблона')),
                ('ai_prompt', models.TextField(blank=True, help_text='Инструкция для DeepSeek при генерации текста', verbose_name='Промпт для ИИ')),
                ('hashtags', models.TextField(blank=True, verbose_name='Хештеги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='posts.postcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шаблон поста',
                'verbose_name_plural': 'Шаблоны постов',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Для внутреннего использования', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст поста')),
                ('content_telegram', models.TextField(blank=True, help_text='Если пустой, используется основной текст', verbose_name='Текст для Telegram')),
                ('content_vk', models.TextField(blank=True, help_text='Если пустой, используется основной текст', verbose_name='Текст для VK')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('draft', '📝 Черновик'), ('pending', '⏳ На модерации'), ('approved', '✅ Одобрен'), ('scheduled', '📅 Запланирован'), ('publishing', '🔄 Публикуется'), ('published', '✔️ Опубликован'), ('failed', '❌ Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Время публикации')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='Сгенерирован ИИ')),
                ('ai_prompt_used', models.TextField(blank=True, verbose_name='Использованный промпт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('platforms', models.ManyToManyField(blank=True, to='posts.platform', verbose_name='Платформы для публикации')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.postcategory', verbose_name='Категория')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.posttemplate', verbose_name='Использованный шаблон')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '✅ Успешно'), ('failed', '❌ Ошибка'), ('pending', '⏳ В процессе')], default='pending', max_length=20, verbose_name='Статус')),
                ('external_id', models.CharField(blank=True, help_text='ID сообщения в Telegram или поста в VK', max_length=100, verbose_name='ID в соцсети')),
                ('external_url', models.URLField(blank=True, verbose_name='Ссылка на пост')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.platform', verbose_name='Платформа')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='posts.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('platforms', models.ManyToManyField(to='posts.platform', verbose_name='Платформы')),
                ('preferred_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.postcategory', verbose_name='Предпочтительная категория')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Расписание публикаций',
                'ordering': ['day_of_week', 'time'],
                'unique_together': {('day_of_week', 'time')},
            },
        ),
    ]
